CREATE TABLE goals(
    goal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    target_amount DECIMAL(15, 2) NOT NULL CHECK (target_amount >= 0),
    current_amount DECIMAL(15, 2) NOT NULL DEFAULT 0.00 CHECK (current_amount >= 0),
    time_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    target_date DATE NOT NULL,
    priority_level VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL
    description VARCHAR(250)
    CONSTRAINT FK_goals_accounts 
        FOREIGN KEY (account_id) 
        REFERENCES accounts(account_id),
);
