ALTER TABLE accounts
ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'USER';

ALTER TABLE accounts
ADD COLUMN profile_picture_url VARCHAR(500);

ALTER TABLE accounts
ADD COLUMN dark_mode_enabled BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE accounts
ADD COLUMN time_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE accounts
ADD COLUMN last_login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

UPDATE accounts SET role = 'USER' WHERE role is NULL;
